name: DupePlusPlus
version: '4.3-SNAPSHOT'
main: me.Pro2021CA.dupePlusPlus.DupePlusPlus
api-version: '1.21'
author: Pro2021CA
commands:
  dupeconfig:
    usage: /<command>
    permission: dupeplusplus.dupeconfig
  blacklist:
    usage: /<command> <list/add/remove/enchants>
    permission: dupeplusplus.blacklist
  dupe:
    permission: dupeplusplus.dupe
    usage: /<command> <amount>
  nondupeable:
    usage: /<command>
    permission: dupeplusplus.nondupe
  maxdupe:
    usage: /<command> <amount>
    permission: dupeplusplus.maxdupe
permissions:
  dupeplusplus.edit:
    description: allows you to edit the blacklisted items
  dupeplusplus.blacklist:
    description: allows you to view the blacklisted items
  dupeplusplus.maxdupe:
    description: allows you to change the max dupe
  dupeplusplus.nondupe:
    description: allows you to blacklist one certain item by adding data to it
  dupeplusplus.dupe.<amount>:
    description: allows you to bypass the normal max dupe